### ISSUE TITLE
0.3.1 TF2Attributes error

### ISSUE THREAD

**Issue by ghost** [Benoist3012/Slender-Fortress-New-Versions#13]
Dear Benoist,

First and foremost, thanks for making the new versions of Slender Fortress. However, the new 0.3.1 is having some issues. Could it be the TF2attributes I am using? But gameplay solo test is fine so far.

L 03/12/2016 - 08:35:22: SourceMod error session started
L 03/12/2016 - 08:35:22: Info (map "slender_hospice_b5") (file "errors_20160312.log")
L 03/12/2016 - 08:35:22: [SM] Plugin encountered error 25: Call was aborted
L 03/12/2016 - 08:35:22: [SM] Native "SetFailState" reported: Could not initialize call to CEconItemSchema::GetAttributeDefinition
L 03/12/2016 - 08:35:22: [SM] Displaying call stack trace for plugin "tf2attributes.smx":
L 03/12/2016 - 08:35:22: [SM]   [0]  Line 142, C:\sourcemod\tf2attributes\tf2attributes.sp::OnPluginStart()
L 03/12/2016 - 08:36:10: [SM] Native "TF2Attrib_SetByName" reported: Plugin owning this native is currently paused.
L 03/12/2016 - 08:36:10: [SM] Displaying call stack trace for plugin "sf2.smx":
L 03/12/2016 - 08:36:10: [SM]   [0]  Line 4823, C:\Users\Benoist\Desktop\sf2 compiler 1.7+\addons\sourcemod\scripting\sf2.sp::Event_PlayerSpawn()
L 03/12/2016 - 08:36:21: [SM] Native "TF2Attrib_SetByName" reported: Plugin owning this native is currently paused.
L 03/12/2016 - 08:36:21: [SM] Displaying call stack trace for plugin "sf2.smx":
L 03/12/2016 - 08:36:21: [SM]   [0]  Line 4909, C:\Users\Benoist\Desktop\sf2 compiler 1.7+\addons\sourcemod\scripting\sf2.sp::Event_PlayerSpawn()
L 03/12/2016 - 08:36:21: [SM] Native "TF2Attrib_SetByName" reported: Plugin owning this native is currently paused.
L 03/12/2016 - 08:36:21: [SM] Displaying call stack trace for plugin "sf2.smx":

Thanks and regards
Sapphire Jasper
-Everyday is a new adventure in the blue sky™-

**Comment by Kenzzer** [comment]
Hi,
It seems your tf2attributes's gamedata is outdated. Can you tell me the OS of your server?

**Comment by ghost** [comment]
Dear Benoist.

Thanks for your reply. I have since fixed the issue. Thanks for helping me validate that the issue is due to an outdated game data!

My server OS is Windows Server 2012 R2 Standard

**Comment by Kenzzer** [comment]
Windows servers with tf2attributes have the most chance to break every tf2updates.
