### ISSUE TITLE
SLPack and Points

### ISSUE THREAD

**Issue by Riotline** [Benoist3012/Slender-Fortress-New-Versions#16]
Everytime I join the server and I do !slpack  it doesn't show anything and everytime I look at credits everyone has 0 and no one joins red. Please help.

**Comment by Kenzzer** [comment]
Can you tell me which server are you joining?

**Comment by Kenzzer** [comment]
Added pending label until an answer from the OP.

**Comment by Kenzzer** [comment]
I still don't have noticed any problems on my test servers and the public servers, and no answers from the OP, I close this issue.
