### ISSUE TITLE
Hitbox! Message Spam

### ISSUE THREAD

**Issue by fearts** [Benoist3012/Slender-Fortress-New-Versions#17]
On map Parish b1b my chat gets spammed with the word Hitbox! over and over. 

Picture: https://gyazo.com/51d13458670bc9c7dd5706fecd4b7478

I looked in the code it seems to be in sf2.sp line 3015. No idea why it's only happening on that map. I could edit the code myself to block it out but I don't want to create a forked version from your releases.

**Comment by Kenzzer** [comment]
Yes I saw it too, thanks for the report. This part of code was never triggered until now, I guess that's why I forgot about it.
