### ISSUE TITLE
Problem with building path

### ISSUE THREAD

**Issue by MAGNAT2645** [Benoist3012/Slender-Fortress-New-Versions#22]
NavMesh plugin wont build path for bosses.
I have SourceMod 1.7.3-5312, Slender Fortress 2 0.3.2c and NavMesh 1.0.4.
Logs:

L 07/13/2016 - 00:09:34: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 07/13/2016 - 00:09:34: [SM] Native "GetNativeCell" reported: Invalid parameter number: 9
L 07/13/2016 - 00:09:34: [SM] Displaying call stack trace for plugin "navmesh.smx":
L 07/13/2016 - 00:09:34: [SM]   [0]  Line 2753, C:\Users\Benoist\Desktop\sf2 compiler 1.7+\addons\sourcemod\scripting\navmesh.sp::Native_NavMeshBuildPath()
L 07/13/2016 - 00:09:34: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 07/13/2016 - 00:09:34: [SM] Native "NavMesh_BuildPath" reported: Error encountered while processing a dynamic native
L 07/13/2016 - 00:09:34: [SM] Displaying call stack trace for plugin "sf2.smx":
L 07/13/2016 - 00:09:34: [SM]   [0]  Line 1509, sf2/npc/npc_chaser.sp::Timer_SlenderChaseBossThink()

P.S. i don't want to install SourceMod 1.8+ for Slender Fortress 2 1.0.0, because when i'm compiling any plugins with compiler 1.8+, he throws for me error: undefined symbol 'MinimumValid_Address'

**Comment by Kenzzer** [comment]
If you can't compile the plugin, just grab the smx from the rispostery.
You should also update your navmesh plugin to the lastest version.

About the compiler error, try to install the lastest version of sourcemod 1.8:  http://www.sourcemod.net/downloads.php?branch=stable

**Comment by MAGNAT2645** [comment]
Tried to use latest SourceMod 1.8.0-5919, but compiler throw to me error:

## undefined symbol 'MinimumValid_Addres'.

Someone: said 'This error appears, when using SourceMod 1.8+ Compiler'.
I can't compile plugin 'TF_Tauntem'.

**Comment by Kenzzer** [comment]
Yeah but this tauntem isn't sf2, I'm closing this issue.

The best you can do is contact the plugin author.
