### ISSUE TITLE
How define boss per map..?

### ISSUE THREAD

**Issue by tigocesar** [Benoist3012/Slender-Fortress-New-Versions#23]
hey!! i'm setup a sf2 server and i have a little inssue with define boss per map. Always, the first boss on profile.cfg is loaded in every map. How i can define the boss for witch map? 
Example:
Guardian - slender_hellfire_b1
Grunt(Amnesia) - slender_cellars_b3
I need to create a boss pack for every map?
etc

Btw, thanks.

**Comment by eNNercY1337** [comment]
the wiki should answer all of your questions.

https://github.com/KitRifty/slender-fortress/wiki/List-of-console-commands-and-variables

**Comment by tigocesar** [comment]
Yeaah..i know about that page bro, 
The problem is when i use sf2_boss_main the boss stay in every map ;-; i tried to create the map cfg and put in cfg folder but it seems the doesn't load :( 
Thanks for the attention eNNercY1337

**Comment by Kenzzer** [comment]
I don't know if you got an answer since then, but be sure your cfg is named that way mapname.cfg, under tf/cfg.
And you don't setup anything in sf2_boss_main under tf/cfg/sourcemod/sf2.cfg

But because that issue is old, I'm gonna close it, feel free to reopen it whenever you want.
