### ISSUE TITLE
New key for config

### ISSUE THREAD

**Issue by MAGNAT2645** [Benoist3012/Slender-Fortress-New-Versions#26]
Key like "download 0/1" will be useful, because i have bosses (TF2 Ghost, Bombonomicon) and their sounds always redownloading when i connect to server.

**Comment by Kenzzer** [comment]
It doesn't need to be added, if sounds keys have been setup correctly to mach tf2 file sound path, you won't have to download them. Can I see your sound paths, of those two bosses?

**Comment by MAGNAT2645** [comment]
But, why TF2 built-in sounds always redownloading if i will add them to StringTables?

**Comment by MAGNAT2645** [comment]
TF2 Ghost
		"sound_spawn_all"
		{
			"1"	"misc/halloween_eyeball/vortex_eyeball_moved.wav"
		}

		"sound_player_death_all"
		{
			"1"	"vo/halloween_boo1.wav"
			"2"	"vo/halloween_boo2.wav"
			"3"	"vo/halloween_boo3.wav"
			"4"	"vo/halloween_boo4.wav"
			"5"	"vo/halloween_boo5.wav"
			"6"	"vo/halloween_boo6.wav"
			"7"	"vo/halloween_boo7.wav"
		}
		
		"sound_scare_player"
		{
			"1"	"ambient/halloween/mysterious_perc_01.wav"
			"2"	"ambient/halloween/mysterious_perc_02.wav"
			"3"	"ambient/halloween/mysterious_perc_03.wav"
		}
		
		"sound_static"
		{
		}
		
		"sound_chase_music"
		{
			"1"	"ambient/halloween/bombinomicon_loop.wav"
		}
		
		"sound_idle"
		{
			"1"	"vo/halloween_moan1.wav"
			"2"	"vo/halloween_moan2.wav"
			"3"	"vo/halloween_moan3.wav"
			"4"	"vo/halloween_moan4.wav"
		}
		
		"sound_alertofenemy"
		{
			"1"	"vo/halloween_haunted1.wav"
			"2"	"vo/halloween_haunted2.wav"
			"3"	"vo/halloween_haunted3.wav"
			"4"	"vo/halloween_haunted4.wav"
			"5"	"vo/halloween_haunted5.wav"
		}
		
		"sound_chasingenemy"
		{
			"1"	"vo/halloween_moan1.wav"
			"2"	"vo/halloween_moan2.wav"
			"3"	"vo/halloween_moan3.wav"
			"4"	"vo/halloween_moan4.wav"
		}

I forget, that i don't have Bombonomicon 😄

**Comment by Kenzzer** [comment]
Well here is your problem, all the sounds are no longer .wav sounds, but .mp3 except the ambient sounds.
It shall fix your problem, close this issue if it fixed your problem, or post another message if it didn't, I'll close it in 2 days, if you forget to do it.

**Comment by MAGNAT2645** [comment]
When valve replaced .wav to .mp3? As i think .wav recently used in 2015.
P.S. This will fix problem, but where i can take more bosses? My server trying to redownloading files that i don't have (but passed in profiles.cfg).

**Comment by Kenzzer** [comment]
They were changed on the 12/03/2015 source: http://www.teamfortress.com/post.php?id=16075

And about that, " where i can take more bosses? My server trying to redownloading files that i don't have (but passed in profiles.cfg", could you reword your sentence please? It's kind of hard to get, and if you want more bosses you have to create them.

**Comment by Kenzzer** [comment]
I close this issue, since the OP didn't reply to my last question, and that the original problem is solved.

**Comment by MAGNAT2645** [comment]
Sorry for this delaying. You can remove 'Waiting answer' label because this problem fixed. ~~I have only one problem with downloads and is "models/demani_sf/key_australium.mdl" (_#define SF_KEYMODEL "models/demani_sf/key_australium.mdl"_ in code (line 72)) (i dont have that model but server trying to precache and download it). Where i can find this model?~~ (Solved)
