### ISSUE TITLE
[SM] Plugin sf2.smx failed to reload: Native "NavMesh_FindAreaByID" was not found.

### ISSUE THREAD

**Issue by ghost** [Benoist3012/Slender-Fortress-New-Versions#29]
Hi,

> [SM] Plugin sf2.smx failed to reload: Native "NavMesh_FindAreaByID" was not found.

I'm using Slender Fortress v1.0.0 lag fix version but it's not loading with this error. I'm using the latest navmesh and slender gamedata, plugins with no edits.

I am running MetaMod:Source v1.10.6V, SourceMod v1.8.0.5951 on Ubuntu 16.04.

Thanks.

**Comment by Kenzzer** [comment]
https://github.com/Benoist3012/sourcepawn-navmesh/blob/master/addons/sourcemod/plugins/navmesh.smx

Are you sure you are using this navmesh plugin? The current one I have for sf2 is the same as that one.

If it keeps happening, you can recompile the plugin, link to the source: https://github.com/Benoist3012/sourcepawn-navmesh/blob/master/addons/sourcemod/scripting/navmesh.sp

**Comment by ghost** [comment]
Great, that fixed it! Thanks!
