### ISSUE TITLE
Precache Error

### ISSUE THREAD

**Issue by rumblefrog** [Benoist3012/Slender-Fortress-New-Versions#30]
I'm unable to discover the issue as TF2 does not provide a crash log :/

But whenever I change to a different map, OnPutInServer, everyone crashes. And if you don't restart the server afterward, you'll see an error model on the boss entity. So I'm assuming it's something to do with models, but I'm unable to confirm it.

**Comment by Kenzzer** [comment]
Sounds like you have wrongly installed slender fortress models on your servers. You must download and installed those zips, [ZIP 1](https://bitbucket.org/KitRifty/slender-fortress/downloads/SF2%20Custom%20Content.zip?pk=544398) & [ZIP 2](https://www.dropbox.com/s/n59uvn2dq0400q3/sf2_0.3.2models.zip?dl=0).

**Comment by rumblefrog** [comment]
@Benoist3012 Those are the ones I downloaded.

**Comment by rumblefrog** [comment]
Upon adding `-condebug` to my startup and I received this:

```
CMaterial::PrecacheVars: error loading vmt file for models/jason278/slender/sheets/sheet_1
CMaterial::PrecacheVars: error loading vmt file for models/jason278/slender/sheets/sheet_2
CMaterial::PrecacheVars: error loading vmt file for models/jason278/slender/sheets/sheet_3
CMaterial::PrecacheVars: error loading vmt file for models/jason278/slender/sheets/sheet_4
CMaterial::PrecacheVars: error loading vmt file for models/jason278/slender/sheets/sheet_5
CMaterial::PrecacheVars: error loading vmt file for models/jason278/slender/sheets/sheet_6
CMaterial::PrecacheVars: error loading vmt file for models/jason278/slender/sheets/sheet_7
CMaterial::PrecacheVars: error loading vmt file for models/jason278/slender/sheets/sheet_8
CMaterial::PrecacheVars: error loading vmt file for models/demani_sf/key_australium
CMaterial::PrecacheVars: error loading vmt file for arrival/slender
CMaterial::PrecacheVars: error loading vmt file for models/zombie_fast/newrake2
CMaterial::PrecacheVars: error loading vmt file for the_sniper_9/doctorwho/extras/angels/angelbody
CMaterial::PrecacheVars: error loading vmt file for the_sniper_9/doctorwho/extras/angels/angelface
CMaterial::PrecacheVars: error loading vmt file for the_sniper_9/doctorwho/extras/angels/angelwings
CAsyncWavDataCache:  24 .wavs total 0 bytes, 0.00 % of capacity
Compact freed 839680 bytes
```

**Comment by Kenzzer** [comment]
Looks like missing files or corrupted files. Not sf2's fault. Or some problems with sv_pure.

**Comment by rumblefrog** [comment]
I can confirm it was an issue on my part. Changed `sv_pure` from `2` to `0`

**Comment by Kenzzer** [comment]
As I said on steam chat it was indeed sv_pure. If you want to use it though, try looking for tutorials on internet, and how setup a white list.
