### ISSUE TITLE
Bosses are not spawning + New versions of Slender Fortress?

### ISSUE THREAD

**Issue by smokers953** [Benoist3012/Slender-Fortress-New-Versions#31]
Hi,

I am just creating a Slender Fortress server for personal use, but the server doesn't seem to be spawning them. Could it possibly be a nav mesh issue? The nav of the map was double checked and it appears to be fine. It occurs on all the maps. I have done troubleshooting on your wiki and it still doesn't work.

Using the latest version of Sourcemod 1.8 (6028) and just barebones SF2.

L 10/21/2017 - 21:00:02: [navmesh.smx] Found .NAV file in maps\slender_hospice_b5c.nav
L 10/21/2017 - 21:00:02: [navmesh.smx] Is mesh analyzed: 1
L 10/21/2017 - 21:00:02: [navmesh.smx] Nav version: 16; SubVersion: 2 (v10+); BSPSize: 78237102; MagicNumber: -17958194
L 10/21/2017 - 21:00:02: [navmesh.smx] Place count: 0
L 10/21/2017 - 21:00:02: [navmesh.smx] Has unnamed areas: true
L 10/21/2017 - 21:00:02: [navmesh.smx] Area count: 588
L 10/21/2017 - 21:00:02: [navmesh.smx] All nav areas parsed into the grid!

L 10/21/2017 - 14:15:27: [sf2.smx] Loading boss profiles from file addons\sourcemod\configs\sf2\profiles.cfg...
L 10/21/2017 - 14:15:27: [sf2.smx] slenderman...
L 10/21/2017 - 14:15:27: [sf2.smx] rake...
L 10/21/2017 - 14:15:27: [sf2.smx] weepingangel...
L 10/21/2017 - 14:15:27: [sf2.smx] Loaded 3 boss profile(s) from file!
L 10/21/2017 - 14:15:27: [sf2.smx] Reloaded restricted weapons configuration file successfully
L 10/21/2017 - 14:17:55: [sf2.smx] Found sf2_maxplayers entity, set maxplayers to 6
L 10/21/2017 - 14:17:55: [sf2.smx] Loaded page music ranges successfully!
L 10/21/2017 - 14:20:35: [sf2.smx] Loaded page music ranges successfully!
L 10/21/2017 - 14:20:51: [sf2.smx] Loaded page music ranges successfully!

![capture](https://user-images.githubusercontent.com/32981907/31852170-b2cfbe56-b6a5-11e7-978d-d88d39082ffa.PNG)

The server does not spawn the boss. When I manually spawn it with Spawn Active Boss, the server gives the error that the boss is not on the nav mesh. 

Another thing to note is, the plugins didn't produce any errors throughout the session.

Also, where do I download your newer versions that are used on the official servers like 1.5.0?

Thanks,
smoker

**Comment by Glubbable** [comment]
Hi, sorry for the late response, but have you tried using the released builds of the gamemode? You can grab it here.

https://github.com/Benoist3012/Slender-Fortress-New-Versions/releases/tag/sf1.0.0
https://github.com/Benoist3012/sourcepawn-navmesh/releases/tag/1.0.4

**Comment by Kenzzer** [comment]
Due to issue inactivity and answer given above I close this issue.
