### ISSUE TITLE
I have a compile error

### ISSUE THREAD

**Issue by Munt39487** [Benoist3012/Slender-Fortress-New-Versions#32]
![thats](https://user-images.githubusercontent.com/33744116/32931687-f49d1e60-cba8-11e7-9a53-6a73d48af011.PNG)
What should I can do? I just downloaded slender fortress 2 new version.. I downloaded include files and Navemash... I openned server August, and I didn't touched server files... I changed new files. I have a error.

**Comment by Kenzzer** [comment]
I said on group announcement it would take some days before i get everything updated for everyone

**Comment by Munt39487** [comment]
okay thanks :)

**Comment by ColterD** [comment]
Has there been any update to the chasepath.sp error?

**Comment by fxss-repository** [comment]
Was not, unfortunately.

**Comment by Munt39487** [comment]
Sad.

**Comment by MAGNAT2645** [comment]
Now compiles without errors but with 266 warnings.

> scripting\include\usermessages.inc(230) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\include\menus.inc(372) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\include\halflife.inc(380) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\include\halflife.inc(411) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\include\sdktools_sound.inc(470) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\include\sdktools_tempents.inc(190) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\include\nativevotes.inc(603) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\include\morecolors.inc(64) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\include\morecolors.inc(159) : warning 219: local variable "team" shadows a variable at a preceding level
> scripting\include\morecolors.inc(251) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\include\morecolors.inc(308) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/debug.sp(94) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/stocks.sp(204) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/stocks.sp(212) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/stocks.sp(847) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/stocks.sp(974) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/stocks.sp(1155) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/stocks.sp(1237) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/profiles/profile_chaser.sp(129) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/profiles/profile_chaser.sp(262) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/profiles.sp(738) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/profiles.sp(749) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/profiles.sp(760) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/profiles.sp(771) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/profiles.sp(787) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/profiles.sp(931) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/profiles.sp(1058) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/profiles.sp(1260) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/nav.sp(315) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/nav.sp(454) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/nav.sp(693) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/nav.sp(724) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/nav.sp(746) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/nav.sp(754) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/effects.sp(66) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(29) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(233) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(268) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(299) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(335) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(355) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(382) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(429) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(470) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(485) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(564) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups.sp(605) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups/menus.sp(250) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups/menus.sp(269) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups/menus.sp(319) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups/menus.sp(339) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups/menus.sp(415) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups/menus.sp(435) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups/menus.sp(558) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/playergroups/menus.sp(578) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/menus.sp(350) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/menus.sp(691) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/menus.sp(778) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/menus.sp(835) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/menus.sp(857) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(269) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(294) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(307) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(322) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(369) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(396) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(413) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(590) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(637) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(757) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(832) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(842) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(861) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(893) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(905) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(942) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(988) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(1150) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(1158) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(1492) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(1569) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(1683) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(1689) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(1744) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(1801) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(1849) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(2006) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(2246) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc.sp(2649) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(421) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(482) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(625) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(740) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(870) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(974) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(1008) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(1106) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(1207) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(3055) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(3113) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(3418) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(3425) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/npc/npc_chaser.sp(3490) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/pvp.sp(247) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/pvp.sp(509) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/pvp.sp(626) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/pvp.sp(681) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(237) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(269) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(293) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(528) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(891) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1015) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1039) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1244) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1277) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1761) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1767) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1831) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1842) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1890) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1897) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(1919) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(2133) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(2975) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(3067) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(3418) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(4068) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(4226) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(4290) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(4476) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(4649) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(4705) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(4871) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5144) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5214) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5284) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5356) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5462) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5493) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5536) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5567) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5610) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5641) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5672) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5715) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5808) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5956) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(5998) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(6130) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(6217) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(6274) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(6488) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(6498) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(6685) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/client.sp(6762) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/specialround.sp(175) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/specialround.sp(183) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/specialround.sp(451) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/specialround.sp(497) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/specialround.sp(521) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/specialround.sp(535) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/specialround.sp(578) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/specialround.sp(602) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/specialround.sp(689) : warning 219: local variable "i" shadows a variable at a preceding level
> sf2/adminmenu.sp(480) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(1457) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(1474) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(1504) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(1577) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(1634) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(2046) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(2230) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(2311) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(2490) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(2553) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(2727) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(2785) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(2797) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(2879) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(2903) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(3011) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(3044) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(3302) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(3490) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(3517) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(3533) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(3627) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(3769) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4018) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4029) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4065) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4076) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4155) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4355) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4365) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4469) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4505) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4589) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4603) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4635) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4762) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4865) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4964) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(5001) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(5032) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(5066) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(5081) : warning 219: local variable "team" shadows a variable at a preceding level
> scripting\sf2.sp(5206) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(5251) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(5258) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(5328) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(5373) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(5407) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(5532) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(6080) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(6199) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(6366) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(6423) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(6456) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(6491) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(6513) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(6582) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(6625) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(6884) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7020) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7063) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7179) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7267) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7460) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7507) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7535) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7552) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7612) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7645) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7658) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(7696) : warning 219: local variable "i" shadows a variable at a preceding level
> scripting\sf2.sp(4426) : warning 203: symbol is never used: "DidClientPlayNewBossRound"
> scripting\sf2.sp(4436) : warning 203: symbol is never used: "DidClientPlaySpecialRound"
> scripting\sf2.sp(407) : warning 203: symbol is never used: "GetChaserProfileAnimationsData"
> scripting\sf2.sp(7127) : warning 203: symbol is never used: "IsNewBossRoundRunning"
> scripting\sf2.sp(111) : warning 203: symbol is never used: "NPCChaserGetMovementActivity"
> scripting\sf2.sp(147) : warning 203: symbol is never used: "NPCChaserSetAirSpeed"
> scripting\sf2.sp(167) : warning 203: symbol is never used: "NPCChaserSetMaxAirSpeed"
> scripting\sf2.sp(157) : warning 203: symbol is never used: "NPCChaserSetMaxWalkSpeed"
> scripting\sf2.sp(112) : warning 203: symbol is never used: "NPCChaserSetMovementActivity"
> scripting\sf2.sp(137) : warning 203: symbol is never used: "NPCChaserSetWalkSpeed"
> scripting\sf2.sp(158) : warning 203: symbol is never used: "NPCGetEnemy"
> scripting\sf2.sp(159) : warning 203: symbol is never used: "NPCSetEnemy"
> scripting\sf2.sp(148) : warning 203: symbol is never used: "SDK_EndTouch"
> scripting\sf2.sp(332) : warning 203: symbol is never used: "SDK_Entity_VPhysicsInitNormal"
> scripting\sf2.sp(139) : warning 203: symbol is never used: "SDK_StartTouch"
> scripting\sf2.sp(1235) : warning 203: symbol is never used: "Slender_HitboxScale"
> scripting\sf2.sp(925) : warning 203: symbol is never used: "TE_DrawBox"
> scripting\sf2.sp(952) : warning 203: symbol is never used: "TE_SendBeam"
> scripting\sf2.sp(171) : warning 203: symbol is never used: "Tutorial_EnableHooks"
> scripting\sf2.sp(160) : warning 203: symbol is never used: "Tutorial_SetupSDK"
> scripting\sf2.sp(33) : warning 204: symbol is assigned a value that is never used: "g_cvDebugBosses"
> scripting\sf2.sp(632) : warning 203: symbol is never used: "g_cvLookAheadDist"
> scripting\sf2.sp(69) : warning 204: symbol is assigned a value that is never used: "g_cvPvPArenaPlayerCollisions"
> sf2/npc/npc_chaser.sp(6) : warning 203: symbol is never used: "g_flSlenderUnStuckPos"
> scripting\sf2.sp(66) : warning 204: symbol is assigned a value that is never used: "g_hCvarAvoidTeammates"
> scripting\sf2.sp(16) : warning 204: symbol is assigned a value that is never used: "g_hCvarEnableTutorial"
> scripting\sf2.sp(91) : warning 204: symbol is assigned a value that is never used: "g_hGetFrictionForward"
> scripting\sf2.sp(94) : warning 204: symbol is assigned a value that is never used: "g_hGetFrictionSideways"
> scripting\sf2.sp(1326) : warning 204: symbol is assigned a value that is never used: "g_iPathLaserModelIndex"

**Comment by Kenzzer** [comment]
You're using sm 1.9 compiler that's why.

**Comment by MAGNAT2645** [comment]
So it works on 1.8 (or 1.10 dev) only? That's sad. I think that 1.9 really good.

**Comment by MAGNAT2645** [comment]
Is there any way to port code to 1.9? I can't find where to change it.

**Comment by Kenzzer** [comment]
Compiling it with a 1.8 sm compiler doesn't mean that it will not work on higher sourcemod version.
There just a thing the sm 1.9 compiler doesn't like and it errors that's all.

**Comment by MAGNAT2645** [comment]
Maybe i can change that thing or you can compile it? I just don't want download 1.8 compiler.

**Comment by Kenzzer** [comment]
If you fix the issue feel free to make a PR.
Also since this issue is "resolved" I'm closing it.
