### ISSUE TITLE
Few Problems...

### ISSUE THREAD

**Issue by Deseaster** [Benoist3012/Slender-Fortress-New-Versions#33]
Hey i have a few problems if you could help me with that?

Rake doesn't attack but instead he slowly walks towards the player i have the latest version of navmesh.smx and i have reinstalled it multiple times still nothing

Errors log:

- L 01/05/2018 - 23:38:41: SourceMod error session started
L 01/05/2018 - 23:38:41: Info (map "slender_scp_087_b_v3b") (file "errors_20180105.log")
L 01/05/2018 - 23:38:41: [SM] Unable to load plugin "navmesh-test.smx": Native "NavMesh_GetAreas" was not found
L 01/05/2018 - 23:39:59: [SM] Exception reported: Invalid address value
L 01/05/2018 - 23:39:59: [SM] Blaming: navmesh.smx
L 01/05/2018 - 23:39:59: [SM] Call stack trace:
L 01/05/2018 - 23:39:59: [SM]   [0] GetNativeCellRef
L 01/05/2018 - 23:39:59: [SM]   [1] Line 3095, C:\hlserver\tf2\tf\addons\sourcemod\scripting\navmesh.sp::Native_NavMeshBuildPath
L 01/05/2018 - 23:39:59: [SM]   [3] NavMesh_BuildPath
L 01/05/2018 - 23:39:59: [SM]   [4] Line 1564, sf2/npc/npc_chaser.sp::Timer_SlenderChaseBossThink
L 01/05/2018 - 23:40:00: [SM] Exception reported: Invalid address value
L 01/05/2018 - 23:40:00: [SM] Blaming: navmesh.smx
L 01/05/2018 - 23:40:00: [SM] Call stack trace:
L 01/05/2018 - 23:40:00: [SM]   [0] GetNativeCellRef
L 01/05/2018 - 23:40:00: [SM]   [1] Line 3095, C:\hlserver\tf2\tf\addons\sourcemod\scripting\navmesh.sp::Native_NavMeshBuildPath
L 01/05/2018 - 23:40:00: [SM]   [3] NavMesh_BuildPath
L 01/05/2018 - 23:40:00: [SM]   [4] Line 1564, sf2/npc/npc_chaser.sp::Timer_SlenderChaseBossThink
L 01/05/2018 - 23:40:00: [SM] Exception reported: Invalid address value

Server doesn't load more bosses. I've properly installed the models, materials and sound files of other bosses, and i did place the boss profile into configs/sf2/profiles.cfg
but still it only loads slenderman, rake and weepingangel :/

Pages spawn when i'm really close to it... they are not there when i'm standing infront of it from a distance, could this be because i'm hosting it from my pc?

**Comment by Glubbable** [comment]
Just a quick question. Are you using the following releases or did you directly download the master zip file of the github deposits?

If not, you can try these releases and tell me if it's ok.

https://github.com/Benoist3012/Slender-Fortress-New-Versions/releases/tag/sf1.0.0
https://github.com/Benoist3012/sourcepawn-navmesh/releases/tag/1.0.4

**Comment by Deseaster** [comment]
Yeah i was using the master zip file this fixed the Rake issue thanks. Now the only problem is that it still doesn't load more bosses from profiles.cfg only Slenderman, Rake,Weepinangel :c

**Comment by Glubbable** [comment]
Check your server console after loading SF2 to see what it prints. It's most likely that the profiles are configured incorrectly.

**Comment by Deseaster** [comment]
This is in the console:

Console initialized.
Using Breakpad minidump system. Version: 4294355 AppID: 232250
server.dll loaded for "Team Fortress"
For FCVAR_REPLICATED, ConVar must be defined in client and game .dlls (sv_use_steam_voice)
ProtoDefs post data loaded.
ProtoDefs loaded. 18.34 MB used
ProtoDefs post data loaded.
ProtoDefs loaded. 18.34 MB used
maxplayers set to 31
No '-replayserverdir' parameter found - using default replay folder.
Replay: Creating thread pool...succeeded.
Replay: Starting thread pool with 4 threads...succeeded.
Cleaning files from temp dir, "C:\hlserver\tf2\tf\replay\server\tmp\" ...no files removed.
ProtoDefs post data loaded.
ProtoDefs post data loaded.
Unknown command "r_decal_cullsize"
--------------------------------------------------------
sv_pure value unchanged (current value is 0).
--------------------------------------------------------
maxplayers set to 31
Network: IP 192.168.178.11, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
Initializing Steam libraries for secure Internet server
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
L 01/06/2018 - 19:59:44: -------- Mapchange to slender_4way_v3 --------
L 01/06/2018 - 19:59:44: [TF2ITEMS] "GiveNamedItem" offset = 475
L 01/06/2018 - 19:59:44: [tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName
Executing dedicated server config file server.cfg
Using map cycle file 'cfg/mapcycle_default.txt'.  ('cfg/mapcycle.txt' was not found.)
material models/weapons/c_items/c_ubersaw_xms has a normal map and $basealphaenvmapmask.  Must use $normalmapalphaenvmapmask to get specular.

material models/weapons/c_items/c_frontierjustice_xmas has a normal map and $basealphaenvmapmask.  Must use $normalmapalphaenvmapmask to get specular.

material models/player/items/all_class/all_class_ring_setting has a normal map and $basealphaenvmapmask.  Must use $normalmapalphaenvmapmask to get specular.

material models/player/items/crafting/coin_invasion has a normal map and $basealphaenvmapmask.  Must use $normalmapalphaenvmapmask to get specular.

Set motd from file 'cfg/motd_default.txt'.  ('cfg/motd.txt' was not found.)
Set motd_text from file 'cfg/motd_text_default.txt'.  ('cfg/motd_text.txt' was not found.)
SV_ActivateServer: setting tickrate to 66.7
The nav mesh needs a full nav_analyze
L 01/06/2018 - 19:59:50: [navmesh.smx] Found .NAV file in maps\slender_4way_v3.nav
L 01/06/2018 - 19:59:50: [navmesh.smx] Is mesh analyzed: 0
L 01/06/2018 - 19:59:50: [navmesh.smx] Nav version: 16; SubVersion: 2 (v10+); BSPSize: 9692540; MagicNumber: -17958194
L 01/06/2018 - 19:59:50: [navmesh.smx] Place count: 0
L 01/06/2018 - 19:59:50: [navmesh.smx] Has unnamed areas: true
L 01/06/2018 - 19:59:50: [navmesh.smx] Area count: 2093
L 01/06/2018 - 19:59:50: [navmesh.smx] All nav areas parsed into the grid!
--------------------------------------------------------
sv_pure value unchanged (current value is 0).
--------------------------------------------------------
Writing cfg/banned_user.cfg.
Writing cfg/banned_ip.cfg.
Server logging enabled.
Server logging data to file logs\L0106004.log
L 01/06/2018 - 19:59:50: Log file started (file "logs\L0106004.log") (game "C:\hlserver\tf2\tf") (version "4294355")
Unknown command "mp_autoteambalance_delay"
Unknown command "mp_autoteambalance_warning_delay"
L 01/06/2018 - 19:59:50: server_cvar: "mp_stalemate_enable" "1"
L 01/06/2018 - 19:59:50: server_cvar: "mp_timelimit" "35"
L 01/06/2018 - 19:59:50: server_cvar: "decalfrequency" "30"
'slender_4way_v3.cfg' not present; not executing.
Server is hibernating
Connection to Steam servers successful.
Assigned anonymous gameserver Steam ID [A:1:701802499:9495].
VAC secure mode is activated.
L 01/06/2018 - 19:59:50: server_cvar: "sm_nextmap" "cp_dustbowl"
L 01/06/2018 - 19:59:50: [sf2.smx] -------- Mapchange to slender_4way_v3 -------
L 01/06/2018 - 19:59:50: server_cvar: "mp_friendlyfire" "1"
L 01/06/2018 - 19:59:50: server_cvar: "sv_tags" "friendlyfire"
L 01/06/2018 - 19:59:50: server_cvar: "sv_tags" "friendlyfire"
L 01/06/2018 - 19:59:50: server_cvar: "mp_flashlight" "1"
L 01/06/2018 - 19:59:50: server_cvar: "mp_autoteambalance" "0"
SetRoundState(0)
L 01/06/2018 - 19:59:50: [sf2.smx] Loading boss profiles from file addons\sourcemod\configs\sf2\profiles.cfg...
L 01/06/2018 - 19:59:50: [sf2.smx] slenderman...
L 01/06/2018 - 19:59:50: [sf2.smx] rake...
L 01/06/2018 - 19:59:50: [sf2.smx] weepingangel...
L 01/06/2018 - 19:59:50: [sf2.smx] Loaded 3 boss profile(s) from file!
L 01/06/2018 - 19:59:50: [sf2.smx] Reloaded restricted weapons configuration file successfully
L 01/06/2018 - 19:59:50: [sf2.smx] Loaded special rounds file!
Connection to game coordinator established.

I downloaded the boss pack from here: https://bitbucket.org/KitRifty/slender-fortress/downloads/SF2_Boss_Pack_29_08_2014.rar
i'm using the boss profile that is included in the bosses rar files still not loading any more bosses

**Comment by Kenzzer** [comment]
Can you send your profiles.cfg please.

**Comment by Deseaster** [comment]
[Profiles.cfg.zip](https://github.com/Benoist3012/Slender-Fortress-New-Versions/files/1609227/Profiles.cfg.zip)

**Comment by Glubbable** [comment]
Line 869 is the issue with your config. You've declared that is where the end of the profile is, so it stops reading the rest of it. But, before you delete it, move it to the very bottom of the file, or else it'll error upon loading as you need to state where the file ends.

Basically, to explain it, is that the brackets act as sections, and each section has an open and close. The very first set of brackets, is the entire files contents that you want the gamemode to read. But since it's closing too early, it stops reading it entirely.

**Comment by Deseaster** [comment]
Yah that fixed it :D thank you so much!
