### ISSUE TITLE
Navmesh Error Messages

### ISSUE THREAD

**Issue by CollinHerber** [Benoist3012/Slender-Fortress-New-Versions#34]
I've recently installed this version of Slender Fortress and followed your installation instruction described in the Wiki.

I've taken a further look into this myself but couldn't find anything that stuck out right away.

Figured I'd post it where people might know more than me.

I'm using the latest release of the navmesh plugin, and the latest code from your plugin.

`Dynamic prop prop_dynamic: no sequence named:` This error comes in more frequently, I don't know if it correlates to the stacktrace I'll link below.

```Dynamic prop prop_dynamic: no sequence named:
L 04/01/2018 - 16:47:01: [SM] Exception reported: Invalid address value
L 04/01/2018 - 16:47:01: [SM] Blaming: navmesh.smx
L 04/01/2018 - 16:47:01: [SM] Call stack trace:
L 04/01/2018 - 16:47:01: [SM]   [0] GetNativeCellRef
L 04/01/2018 - 16:47:01: [SM]   [1] Line 3095, C:\Users\Benoist\Desktop\sf2 compiler 1.7+\addons\sourcemod\scripting\navmesh.sp::Native_NavMeshBuildPath
L 04/01/2018 - 16:47:01: [SM]   [3] NavMesh_BuildPath
L 04/01/2018 - 16:47:01: [SM]   [4] Line 1564, sf2/npc/npc_chaser.sp::Timer_SlenderChaseBossThink```

**Comment by CollinHerber** [comment]
Further details:

The only two bosses that work correctly are Slender and Weeping Angel. I've removed the rest of the them, and restarted the server but the error messages still come through. I've installed pretty much all of the bosses that are included in your wiki pages as extras, and none of them worked properly. They would either move extremely slow, or do no damage. Sometimes both. 

Upon figuring this issue out, and after further investigation on my end, I will look into the boss issues and relay that information to a separate issue.


More info: I've confirmed this is true on all maps. I've installed almost all of the special maps/survival maps included in the wiki.

**Comment by Glubbable** [comment]
Hi, could you please install the following from these release downloads and tell me if everything is working?

https://github.com/Benoist3012/Slender-Fortress-New-Versions/releases/tag/sf1.0.0
https://github.com/Benoist3012/sourcepawn-navmesh/releases/tag/1.0.4

**Comment by CollinHerber** [comment]
As said in the issue, I already have the latest releases of each of the mods.

**Comment by Glubbable** [comment]
Downloading the master directory isn't the latest stable release.

**Comment by CollinHerber** [comment]
Let me repeat myself:
 I already have the latest **releases** of each of the mods.

EDIT: I just overwrote all the files, and the file sizes matched 100%

EDIT2: Looking into it myself now as I just got back from my Easter Dinner

**Comment by Glubbable** [comment]
This error only pops up if you downloaded the wrong version of the navmesh plugin. Which is why I asked you, to please download the releases I linked and tell me if they load or not.

**Comment by CollinHerber** [comment]
I put up a second server and installed the fresh plugins and the issue did not occur. I'll have to assume it's something on my initial install and go from there. Could be one of the nine thousand things I added as well.

This can be closed.
