### ISSUE TITLE
Exception reported: NULL not allowed

### ISSUE THREAD

**Issue by legoj15** [Benoist3012/Slender-Fortress-New-Versions#35]
Hello there! After compiling the latest (e1922be) sf2.smx, every time a boss spawns on my server, it crashes with this:
```L 09/01/2018 - 15:02:03: [SM] Exception reported: NULL not allowed
L 09/01/2018 - 15:02:03: [SM] Blaming: sf2.smx
L 09/01/2018 - 15:02:03: [SM] Call stack trace:
L 09/01/2018 - 15:02:03: [SM]   [0] SDKCall
L 09/01/2018 - 15:02:03: [SM]   [1] Line 195, sf2/nextbot/nextbot.sp::NextBotGroundLocomotion.SetVelocity
L 09/01/2018 - 15:02:03: [SM]   [2] Line 1897, sf2/npc/npc_chaser.sp::SlenderChaseBossProcessMovement

**Comment by Kenzzer** [comment]
That's strange, but thanks for report I'll make sure to fix it.

**Comment by Kenzzer** [comment]
Alright NULL issue has been fixed, although It wasn't the reason for your server crash.
It's an issue with the navmesh plugin, please download and compile the latest version:
https://github.com/Benoist3012/sourcepawn-navmesh

**Comment by legoj15** [comment]
Thanks!
