### ISSUE TITLE
Failed to retrieve certain gamedata + CollisionHooks problem

### ISSUE THREAD

**Issue by Mentrillum** [Benoist3012/Slender-Fortress-New-Versions#36]
After installing the required plugins to run SF2, I always get this specific error
![8f2a40bc8ee58f48ea726c318aa32f9d](https://user-images.githubusercontent.com/42941613/44994193-58fdb080-af52-11e8-826a-64cdbdec72f7.png)
I'm unsure if I'm missing something, I even looked in the sf2.sp to find what I was missing, which brings me to my next point, CollisionHooks. Every time I launch my server and spawn any boss, it just straight up crashes with no error or anything, just closes.

This all comes to a point that either I have outdated CollisionHooks files like gamedata, or I'm missing something for SF2 in general to fix the animation error. Before I got the CollisionHooks error, it always said it loaded successfully, but now it doesn't say it has loaded. I tried changing the gamedata numerous times in CollisionHooks from what the forums offered people, but for some reason I cannot find it.

If you have any solution to the CollisionHooks and animation problem, even if its just a slight plugin fix, please let me know.

**Comment by Kenzzer** [comment]
Windows is unsupported, and will remain like so.
Sorry.
