### ISSUE TITLE
Not a issue, but a question about profiles.cfg

### ISSUE THREAD

**Issue by Mentrillum** [Benoist3012/Slender-Fortress-New-Versions#39]
After getting 1.5.0 in my hands, or the lack of my hands as someone got it for me to where I can make bosses for his server, I was beginning to question. What is the new boss codes like the multiple animation system, the multiple attack system, disappearing on hit, etc. Some of these new codes like "bleed player on hit" are self explanitory, but others, specifically the multiple attack and animation system I need information on how to do it.

I might have asked you 10 months ago, but I never got a response, and I cannot find a update to the profiles.cfg with the new boss codes. I'll say it once, and I'll say it again. Is it possible you can provide everyone who is interested into making custom bosses the new boss codes?

**Comment by leo0215** [comment]
i remember 1.5.0's profile.cfg have code function explain and list in header (bad english,sorry)
