### ISSUE TITLE
Server Crash when saw a boss (1.5.0) Linux

### ISSUE THREAD

**Issue by leo0215** [Benoist3012/Slender-Fortress-New-Versions#40]
hi,i testing this new version,but when i saw a boss and server crashed..

> L 09/20/2018 - 19:32:13: [SM] Exception reported: NULL not allowed
> L 09/20/2018 - 19:32:13: [SM] Blaming: sf2.smx
> L 09/20/2018 - 19:32:13: [SM] Call stack trace:
> L 09/20/2018 - 19:32:13: [SM]   [0] SDKCall
> L 09/20/2018 - 19:32:13: [SM]   [1] Line 201, sf2/nextbot/nextbot.sp::NextBotGroundLocomotion.SetVelocity
> L 09/20/2018 - 19:32:13: [SM]   [2] Line 1897, sf2/npc/npc_chaser.sp::SlenderChaseBossProcessMovement
> L 09/20/2018 - 19:32:14: [sf2.smx] [TW]Seyana spawned boss 0! (rake)
> Can't compute incursion distances from the Red spawn room(s). Bots will perform poorly. This is caused by either a missing func_respawnroom, or missing info_player_teamspawn entities within the func_respawnroom.
> Entity 521 (class 'tf_glow') reported ENTITY_CHANGE_NONE but 'm_hTarget' changed.
> Wrote minidump to: /media/ysserver/120g-ssd-tf2/sf2/tf/addons/sourcemod/data/dumps/6e8c4057-5b94-e771-6cd070fd-26c7b13f.dmp
> Segmentation fault (core dumped)
> 

and when starting server,navmesh result this 

The nav mesh needs a full nav_analyze

thanks

**Comment by Kenzzer** [comment]
Update your sourcepawn navmesh
https://github.com/Benoist3012/sourcepawn-navmesh
Compile the latest version.
