### ISSUE TITLE
Some Errors(in linux)

### ISSUE THREAD

**Issue by Munt39487** [Benoist3012/Slender-Fortress-New-Versions#41]
L 09/21/2018 - 21:04:22: [SM] Exception reported: NULL not allowed
L 09/21/2018 - 21:04:22: [SM] Blaming: sf2.smx
L 09/21/2018 - 21:04:22: [SM] Call stack trace:
L 09/21/2018 - 21:04:22: [SM]   [0] SDKCall
L 09/21/2018 - 21:04:22: [SM]   [1] Line 201, sf2/nextbot/nextbot.sp::NextBotGroundLocomotion.SetVelocity
L 09/21/2018 - 21:04:22: [SM]   [2] Line 1897, sf2/npc/npc_chaser.sp::SlenderChaseBossProcessMovement
my error log : / not crashed but these are too many in my error logs

**Comment by leo0215** [comment]
Update your sourcepawn navmesh
https://github.com/Benoist3012/sourcepawn-navmesh
Compile the latest version.

**Comment by Munt39487** [comment]
I did it but not crashed these errors in error log a lot
