### ISSUE TITLE
Exception reported: NULL not allowed and CBaseAnimating errors

### ISSUE THREAD

**Issue by fxss-repository** [Benoist3012/Slender-Fortress-New-Versions#42]
Yes, this is another issue with SDKCall.
The server runs on Windows 10.
Plugin NavMech updated to the latest version.

L 10/11/2018 - 12:57:41: [SM] Blaming: sf2.smx
L 10/11/2018 - 12:57:41: [SM] Call stack trace:
L 10/11/2018 - 12:57:41: [SM]   [0] SDKCall
L 10/11/2018 - 12:57:41: [SM]   [1] Line 201, sf2/nextbot/nextbot.sp::NextBotGroundLocomotion.SetVelocity
L 10/11/2018 - 12:57:41: [SM]   [2] Line 1897, sf2/npc/npc_chaser.sp::SlenderChaseBossProcessMovement

The error is not critical.
The server works as usual, but the console is spamming with errors, such as I have indicated above.

**Comment by WOLFA22** [comment]
I noticed a strange thing.
When this error crashes, the VAR on the server rises sharply to 9ms.

**Comment by fxss-repository** [comment]
When the server is loaded, I see mistakes:

Failed to retrieve CBaseAnimating::LookupSequence signature!
Failed to retrieve CBaseAnimating::LookupPoseParameter signature!
Failed to retrieve CBaseAnimating::SetPoseParameter signature!

How to correct it?

**Comment by Munt39487** [comment]
Because windows has not supported :(

**Comment by fxss-repository** [comment]
Windows not supported?

I do not believe that the server on Linux so strongly differs from Windows. Maybe the developer will make something with it?

In that case, I restore 1.0.0 version. ¯\_ツ_/¯

**Comment by fxss-repository** [comment]
Benoist3012, specify on the homepage that the latest version 1.5.0 only for the Linux operating systems.

**Comment by Munt39487** [comment]
I heard he will not support windows because he has no time and linux coding easier than windows. Sadly :(

**Comment by Glubbable** [comment]
If you want it to work for Windows you'll need to find someone who's willing to hunt down the Windows Signatures for the following.

"CBaseAnimating::SetPoseParameter"
"CBaseAnimating::LookupPoseParameter"
"CBaseAnimating::LookupSequence"

**Comment by Munt39487** [comment]
I found them but bosses are t-posed so i changed to linux i think it needs more code

**Comment by fxss-repository** [comment]
Munt, if u found signatures, throw off the corrected gamedata file here, and developers can be will write a code under Windows.

But it seems to me that they will not complete fashion under Windows.

**Comment by Glubbable** [comment]
I've updated the install guide to state that SF2 is only supported under Linux for the time being.

**Comment by fxss-repository** [comment]
Glubbable, In the future u will add a code under Windows, or not?
To me to wait for SF2 updates or not?

**Comment by Glubbable** [comment]
I'm in no position to make any promises about it sadly. Plus Benoist is way more familar with stuff like this. And would also be able to explain why supporting Windows isn't as easy as it seems.

**Comment by fxss-repository** [comment]
ok...

**Comment by Kenzzer** [comment]
I added windows signatures but if they break due to a game update I won't be there to fix them. This mod requires too much of time so I discontinued it, and I only work on a private version. This is my last update on the public mod.
