### ISSUE TITLE
problem with the boss pack

### ISSUE THREAD

**Issue by ManuHiu** [Benoist3012/Slender-Fortress-New-Versions#43]
I have a problem with my slender server I already made a boss package and I put the classic boss package but the problem is when I start the server and I write /slpack nothing appears and the bosses that are in the pack do not appear

**Comment by Glubbable** [comment]
Did you add the profile pack to the packs list under profiles_packs.cfg?

**Comment by ManuHiu** [comment]
no

**Comment by ManuHiu** [comment]
the file profiles_packs.cfg I have it like this:  // Slender Fortress - Boss Profile Packs is where all profile packs are referenced. A profile pack is a config file that has the same format as the profiles.cfg file, and is essentially the same thing.
// However, profile packs are used to separate groups of bosses away from the main profiles.cfg file, in order to cut down download times and increase chances of
// certain bosses to appear. In short, bosses defined in profiles.cfg will always be loaded, while bosses defined in profile packs CAN be loaded, provided that the pack
// is set to load before a map change.
//
// This decision is usually determined by player votes by the end of the map, or can be overridden by an admin. Boss packs will not be loaded until the next map change.
// Filepaths for packs are relative to sourcemod/configs/sf2/profiles/packs.
// For example:
//
//	"Profile Packs"
//	{
//		"packs"
//		{
//			"pack1"
//			{
//				"name"	"Boss Pack 1"
//				"file"	"pack1.cfg"
//				"autoload"	"0"			// Don't have to define this, default is 0
//				"show_in_vote"	"1"		// Or this either, default is 1
//			}
//		}
//	}
//
// Bosses defined in profiles.cfg will be loaded first, then bosses found in sourcemod/configs/sf2/profiles/packs/pack1.cfg will be loaded after.
// Note that you can also overwrite bosses defined in profiles.cfg via profile packs. However, attributes defined in profiles.cfg WILL NOT CARRY OVER! In other words,
// if you decide to make a boss named "slenderman" in pack1.cfg and "slenderman" is already defined in profiles.cfg, the game will use the "slenderman" profile in
// pack1.cfg instead.
//
// Packs can also be set to autoload, meaning that they will always be loaded after every map change after profiles.cfg is loaded. This can be useful to organize bosses
// into set groups, so as to reduce the amount of bosses in the main config. Also, packs with autoload set to 1 will never be included in end votes, as it would be 
// redundant to do so.
//
//
// CVars:
// sf2_boss_profile_pack - The boss pack referenced in this file that should be loaded.
// sf2_boss_profile_pack_default - If the boss pack defined in sf2_boss_profile_pack is blank or could not be loaded, this pack will be used instead. This cvar should be used to set the initial boss pack upon server startup. Default is ""
// sf2_boss_profile_pack_endvote - Enables/Disables a boss pack vote at the end of the map. Set this to 1 to enable voting. Default is 0.
// sf2_boss_profile_pack_endvote_start - Specifies when to start the vote based on time remaining on the map, in minutes. Default is 4. 
// sf2_boss_profile_pack_endvote_startround - Specifies when to start the vote based on rounds remaining on the map. Default is 2.
// sf2_boss_profile_pack_endvote_shuffle - Shuffles the menu options of boss pack endvotes if enabled.
//
//	"Profile Packs"
//	{
//		"packs"
//		{
//			"classic_pack"
//			{
//				"name"	"Classic Pack"
//				"file"	"classicpack.cfg"
//				"autoload"	"0"			// Don't have to define this, default is 0
//				"show_in_vote"	"1"		// Or this either, default is 1
//			}
//		}
//	}
//  "dr_trager_pack"
//  {
//      "name"  "Dr Trager Pack"
//      "file"  "drtragerpack.cfg"
//      "autoload"  "0"
//      "show_in_vote"  "1"
//  }

**Comment by ManuHiu** [comment]
//	"Profile Packs"
//	{
//		"packs"
//		{
//			"classic_pack"
//			{
//				"name"	"Classic Pack"
//				"file"	"classicpack.cfg"
//				"autoload"	"0"			// Don't have to define this, default is 0
//				"show_in_vote"	"1"		// Or this either, default is 1
//			}
//		}
//	}
//  "dr_trager_pack"
//  {
//      "name"  "Dr Trager Pack"
//      "file"  "drtragerpack.cfg"
//      "autoload"  "0"
//      "show_in_vote"  "1"
//  }

**Comment by Glubbable** [comment]
You commented out the whole section, that's why it's not being read.
