### ISSUE TITLE
Stair turning teleport bug

### ISSUE THREAD

**Issue by TehPlayer14** [Benoist3012/Slender-Fortress-New-Versions#6]
Happens on tomb and other maps with stairs

**Comment by Kenzzer** [comment]
This is a common issue, you have to remember it's a plugin's AI=server resources expensive, so until I find a better way to make "boss's steps", this issue can't be fixed, only "reduced", the last [update](https://github.com/Benoist3012/Slender-Fortress-New-Versions/releases/tag/sf0.2.9) has almost fixed this bug.
