### ISSUE TITLE
Buggy boss moving

### ISSUE THREAD

**Issue by Dalix** [Benoist3012/Slender-Fortress-New-Versions#7]
I installed 0.2.9 navmesh fix and still happen this

**Comment by Glubbable** [comment]
You need to recompile the .sp under sm 1.6 since Benoist forgot to upload it.

**Comment by Dalix** [comment]
Thanks

**Comment by Dalix** [comment]
I got this error:

L 01/29/2016 - 06:54:01: [SM] Plugin encountered error 3: Not enough space on the heap
L 01/29/2016 - 06:54:01: [SM] Displaying call stack trace for plugin "navmesh.smx":
L 01/29/2016 - 06:54:01: [SM]   [0]  Line 1557, C:\Team Fortress 2 - Dedicated Server\server\tf\addons\sourcemod\scripting\navmesh.sp::NavMeshGridFinalize()
L 01/29/2016 - 06:54:01: [SM]   [1]  Line 1381, C:\Team Fortress 2 - Dedicated Server\server\tf\addons\sourcemod\scripting\navmesh.sp::NavMeshLoad()
L 01/29/2016 - 06:54:01: [SM]   [2]  Line 147, C:\Team Fortress 2 - Dedicated Server\server\tf\addons\sourcemod\scripting\navmesh.sp::OnMapStart()

**Comment by Glubbable** [comment]
I said to compile it under sm 1.6.

**Comment by Kenzzer** [comment]
Yeah I forgot to upload it sorry.
